version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-vue-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0
    container_name: laravel-vue-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
